### ISSUE TITLE
Reproducible crash in `DisplayMapFromMobileMapPackageView`

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-samples#113]
It occurs when the Yellowstone mmpk file is force unwrapped on line 36. This seems to reliably happen when the sample is _not_ the first sample to be opened on a fresh install. If I perform a fresh install, open another sample and then this one, I can reliably produce a crash here.

**Comment by yo1995** [comment]
Reproducible, still related to the on demand resource loading timing 🤕

**Comment by yo1995** [comment]
Hope this is fixed with #48
