### ISSUE TITLE
[Sketch on map] Crash when deleting mid vertex

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-samples#158]
1. Create a new line or area based sketch
2. Attempt to delete a mid vertex

> Fatal error: Precondition failed. Illegal state. A mid vertex element can't be deleted.

Should we add more protection against a user triggering this condition?

**Comment by yo1995** [comment]
Hmm, I don't think there is an easy way to catch or handle this precondition fatal error in the app level. Basically, the user is just selecting a vertex and try to remove it, which we don't have a way from the API to tell us that is invalid except this error.

Do you think this should be an API level change?

**Comment by dfeinzimer** [comment]
> Do you think this should be an API level change?

Not necessarily, as shown in the PR (#160), thanks to [canDelete](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/geometryeditorelement/candelete). We may want to document the precondition though.

**Comment by yo1995** [comment]
Fixed in #160 , will go in 200.1 release.
