### ISSUE TITLE
Redirect Create and Edit Geometries from Sketch On Map  - 404 Error

### ISSUE THREAD

**Issue by maryharvey** [Esri/arcgis-maps-sdk-swift-samples#376]
The 200.1 Release Notes for Swift point to a Sketch on Map Sample. See : https://developers.arcgis.com/swift/release-notes/prior-releases/release-notes-for-200-1/#changes-in-samples

Can you add a redirect to take the user from Sketch on Map to  Create and Edit Geometries?

This will get rid of a constant 404 error in our doc. Thanks

**Comment by yo1995** [comment]
#379
