### ISSUE TITLE
Documentation: Runtime reference

### ISSUE THREAD

**Issue by vquach2404** [Esri/arcgis-maps-sdk-swift-samples#414]
There is a reference to **ArcGIS Runtime** in the Navigate in AR [sample](https://viv-add-videos-preview.sites.afd.arcgis.com/swift/#from-our-videos).

We need to replace all "ArcGIS Runtime" with "ArcGIS Maps SDK"

**Comment by yo1995** [comment]
- [ ] Play KML tour/README.md
- [ ] Augment reality to collect data/README.md
- [ ] Find route in transport network/README.md, portal item URL
- [ ] Show mobile map package expiration date/README.md, portal item URL
- [ ] Augment reality to navigate route/README.md
