### ISSUE TITLE
Fix raster file download problem in `Add raster from file`

### ISSUE THREAD

**Issue by yo1995** [Esri/arcgis-maps-sdk-swift-samples#48]
Problem was in #46 

See https://github.com/Esri/arcgis-runtime-samples-ios/pull/1036

The problem's behavior is that when the raster file is downloaded for the first time, it would throw a build failure due to the file not found error. In the following builds, the error is gone.

It may be due to the raster file rely on a certain folder structure, and we have to move back to the old raster portal item. See `common-samples/issues/3618` for the data change.

**Comment by yo1995** [comment]
Display map from mobile map package may also suffer from this problem.

**Comment by yo1995** [comment]
This could potentially be fixed by #107 , need to test

**Comment by yo1995** [comment]
Try to check the flag instead of the percentage progress here: https://github.com/Esri/arcgis-maps-sdk-swift-samples/blob/main/Shared/Supporting%20Files/Models/OnDemandResource.swift#L57

**Comment by CalebRas** [comment]
This is also an issue with #193. The on-demand image data fails to load the first time the app launches. If the local data isn't cleared, the animated image overlay load correctly the second time the app is launched.

**Comment by yo1995** [comment]
Let's hope the fix in #208 is the root cause.
